### ISSUE TITLE
Braswell: FSP Integration Guide of-of-date

### ISSUE THREAD

**Issue by miczyg1** [IntelFsp/FSP#16]
The Braswell FSP Integration Guide states that the base address for FSP binary is `0xfff20000`. However, current MR2 release FSP binary base address is `0xfff9c000`. Could You please update the documentation or the binary?

**Comment by nate-desimone** [comment]
`0xfff20000` is the base address for the regular version of BSW FSP. `0xfff9x000` is the base address for the Secure Boot version of FSP.

There is a build flag that controls which version of the FSP binary is generated at compile time.

I believe the confusion comes from the fact that the MR1 release gave a regular build whereas the MR2 release gave a Secure Boot build. We have posted updated versions of BSW FSP (1.1.7.0 and 1.1.8.0) and we were careful to give both the regular and Secure Boot versions of the BSW FSP binary this time.

https://github.com/IntelFsp/FSP/tree/master/BraswellFspBinPkg/FspBin
https://github.com/IntelFsp/FSP/tree/master/BraswellFspBinPkg/FspBin/SecureBootEnabled

We have also updated the FSP integration guide to clarify that each version has a difference base address. Hope that helps.
