### ISSUE TITLE
Braswell: Different FSP signatures

### ISSUE THREAD

**Issue by i-c-o-n** [IntelFsp/FSP#17]
With d1c99a5 (MR2 version of Braswell FSP) the FSP_IMAGE_ID changed from `$BSWFSP$` to `BSWSBFSP`. What was the reason for this change? Does this refer to different branches of FSP?

**Comment by nate-desimone** [comment]
$BSWFSP$ is the signature for the regular version of BSW FSP. BSWSBFSP is the signature for the Secure Boot version of FSP.

There is a build flag that controls which version of the FSP binary is generated at compile time.

I believe the confusion comes from the fact that the MR1 release gave a regular build whereas the MR2 release gave a Secure Boot build. We have posted updated versions of BSW FSP (1.1.7.0 and 1.1.8.0) and we were careful to give both the regular and Secure Boot versions of the BSW FSP binary this time.

https://github.com/IntelFsp/FSP/tree/master/BraswellFspBinPkg/FspBin
https://github.com/IntelFsp/FSP/tree/master/BraswellFspBinPkg/FspBin/SecureBootEnabled

Hope that helps.
