### ISSUE TITLE
Denverton: Inconsistent type names

### ISSUE THREAD

**Issue by felixsinger** [IntelFsp/FSP#20]
Currently the Denverton FSP headers use `FSP{T,M,S}_CONFIG` as type name. All of the other FSP2 platforms use `FSP_{T,M,S}_CONFIG`.

Please change that to be consistent.

**Comment by veusebio** [comment]
thanks for bringing this to our attention. Will have this fixed.

**Comment by veusebio** [comment]
We have changed the names of the UPD structs. Thanks. Will close this issue.
