### ISSUE TITLE
[Security] FSP TRR support

### ISSUE THREAD

**Issue by zaolin** [IntelFsp/FSP#23]
Hey guys, @nate-desimone,

Does the FSP support TRR on DDR4 memory for rambleed
attack mitigation https://rambleed.com/ ?

If so which UPD option enables it?

BR, Philipp

**Comment by c0d3z3r0** [comment]
@nate-desimone ping!

**Comment by nate-desimone** [comment]
Hey @zaolin, @c0d3z3r0 

Ultimately the rambleed attack relies on being able to induce bit flips using the rowhammer technique. Therefore, our hardware protection against rowhammer is effective against rambleed as well. The UPD is FspmUpd->FspmConfig.RhSolution. The default value for the UPD is to enable the hardware based protection.

Hope that helps.

**Comment by nate-desimone** [comment]
Any objections to closing this one?
