### ISSUE TITLE
Inconsistent folder structure

### ISSUE THREAD

**Issue by krystian-hebel** [IntelFsp/FSP#3]
Folder structure is inconsistent, most of platforms have binary files in FspBin subfolder, while Kabylake and CoffeeLake have theirs binaries in main platform folder.

**Comment by pietrushnic** [comment]
These cause problems when trying to automate build process and integration in projects like coreboot. Ideally would be if directory structure would be consistent.

@vincent-j-zimmer  FYI

**Comment by vincentjzimmer** [comment]
thanks for the feedback. 
@nate-desimone-intel has been doing a nice job of cleaning up the tree.  Being consistent makes sense.

**Comment by swong23** [comment]
Closing this Issue#3 as @nate-desimone-intel had been doing a nice job of cleaning up the tree.
