### ISSUE TITLE
KabylakeFspBinPackage: Crash in FSP

### ISSUE THREAD

**Issue by PatrickRudolph** [IntelFsp/FSP#30]
If PchHdaVcType is zero in FSP_SIL_UPD the FSP-S crashes due to NULL pointer dereference.
As the Hda/Azalia device is disabled on my board, I don't see why this needs to be set at all.

**Comment by c0d3z3r0** [comment]
Additional info: @PatrickRudolph has a Supermicro X11SSH board. On a very similiar board (Supermicro X11SSM) this does not happen with PchHdaVcType=0

**Comment by c0d3z3r0** [comment]
@Intel ping!

**Comment by nate-desimone** [comment]
@PatrickRudolph, @c0d3z3r0, please file this in the [Intel® Premier Support](https://www.intel.com/content/www/us/en/design/support/ips/training/access-and-login.html) system and our Application Engineering department will work with you to resolve the issue.

**Comment by c0d3z3r0** [comment]
@nate-desimone I don‘t have Premier Support. Please forward this internally

**Comment by PatrickRudolph** [comment]
@nate-desimone Please be aware that contributors might not be able to use "Intel Premier Support" as they aren't part of any company or doesn't have an "Intel representative" they could contact.
It makes me sad to see how Intel threads individuals of the Open Source community, by
a. Not responding within month,
b. Closing bug-reports without even confirming that the issue exists,
c. Pointing to unusable internal bugtrackers.
For me your business model looks very questionable. One might think Intel doesn't care if it ships broken (and possibly insecure) software.
