### ISSUE TITLE
CoffeelakeFspBinPkg: Fix Inconsistent File Naming Convention in Fsp.fd

### ISSUE THREAD

**Issue by makubacki** [IntelFsp/FSP#31]
The file in CoffeelakeFspBinPkg has the name "FSP.fd". In other FspBinPkg directories, the convention is "Fsp.fd". The request is to use "Fsp.fd" so generic scripts in case-sensitive operating systems can generically handle this file.

**Comment by nate-desimone** [comment]
Hi @makubacki, sure we would be happy to. Done: https://github.com/IntelFsp/FSP/commit/573bd5d6861376c8b4947d177dfe70592ff80fc2
