### ISSUE TITLE
Microcode for E3825 

### ISSUE THREAD

**Issue by asa1365** [IntelFsp/FSP#46]
Hello, 

I am trying to compile coreboot for E3825. 
It need Microcode file . 
How to get them from FSP files ?
In the past it was with FSP files. 

Best

**Comment by nate-desimone** [comment]
Hi @asa1365, to my knowledge we have never embedded microcode updates in the FSP. Intel microcode updates are distributed through different means.

I am aware of two sources of public distribution of microcode:

1. Linux kernel microcode repo: https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files
2. TianoCore: https://github.com/tianocore/edk2-non-osi

For your specific Bay Trail processor, we have microcode available here: https://github.com/tianocore/edk2-non-osi/tree/master/Silicon/Intel/Vlv2SocBinPkg/Microcode
