### ISSUE TITLE
Broadwell-DE FSP

### ISSUE THREAD

**Issue by zaolin** [IntelFsp/FSP#5]
@nate-desimone-intel  Currently headers and sample code are missing in the repository. Can you add the missing ones?

**Comment by zaolin** [comment]
Also maybe update them?

**Comment by nate-desimone-intel** [comment]
Hi @zaolin, I see the following: https://github.com/IntelFsp/FSP/blob/master/BroadwellDEFspBinPkg/include/fspvpd.h

Is there something more you are looking for?

**Comment by zaolin** [comment]
Yep @nate-desimone-intel https://review.coreboot.org/cgit/coreboot.git/tree/src/vendorcode/intel/fsp1_0/broadwell_de/include
https://review.coreboot.org/cgit/coreboot.git/tree/src/vendorcode/intel/fsp1_0/broadwell_de/srx

**Comment by nate-desimone-intel** [comment]
Hi @zaolin, when comparing the contents of both repos, they are identical:
https://github.com/IntelFsp/FSP/tree/master/BroadwellDEFspBinPkg/include
https://review.coreboot.org/cgit/coreboot.git/tree/src/vendorcode/intel/fsp1_0/broadwell_de/include

![diff](https://user-images.githubusercontent.com/34044982/48087919-84508600-e1b5-11e8-8e3b-5b74e9df2a9f.png)

The copy of fspvpd.h in github is newer than the version in the coreboot repo:

![file_diff](https://user-images.githubusercontent.com/34044982/48088076-e01b0f00-e1b5-11e8-8690-6d8356cf4d9f.png)

The fspsupport.c file is also present in github, just under a different directory structure. I am closing this issue.
