### ISSUE TITLE
FSP tooling only support FSP 2.0

### ISSUE THREAD

**Issue by zaolin** [IntelFsp/FSP#7]
The FSP tooling which is needed for rebasing only supports FSP 1.0.
Is there a way that Intel adds 1.0 and 1.1 support as well?

**Comment by zaolin** [comment]
@nate-desimone-intel Because currently a lot FSP 1.0 and 1.1 related stuff are available with coreboot.

**Comment by nate-desimone-intel** [comment]
Hi @zaolin, you are correct that SplitFspBin.py does not work for FSP 1.x binaries. For these older FSPs, one must use BCT to do the rebase:

https://github.com/IntelFsp/BCT

I realize that this is not ideal. I recommend that we put a feature request to have SplitFspBin.py support FSP 1.x binaries in the tianocore bugzilla: https://bugzilla.tianocore.org/ Would you like me to file this request on your behalf, or would you prefer to do so?

**Comment by zaolin** [comment]
If you have an account, please do it.

**Comment by nate-desimone** [comment]
Fixed in 0bc2b07e.
