### ISSUE TITLE
FSP Broadwell DE not up-to-date

### ISSUE THREAD

**Issue by zaolin** [IntelFsp/FSP#8]
Hey folks,

We are having trouble finding the Broadwell DE MR2 Gold release on
Github. Any information if you can make it available?

**Comment by zaolin** [comment]
@nate-desimone-intel any info?

**Comment by nate-desimone-intel** [comment]
Hi @zaolin,

It looks like commits 5f52d604..0c80d1d1 added the MR2 release to this repo under master branch. Is this what you are looking for?

**Comment by zaolin** [comment]
Yep missed the update. I tried to use it with the current coreboot tree. I don't know if this is a platform issue but the FSP stop working.
