### ISSUE TITLE
Microcode update availability

### ISSUE THREAD

**Issue by pgeorgi** [IntelFsp/FSP#9]
FSP provides only the platform binaries. To boot recent hardware, there's also the FIT to fill out, which also includes pointers to microcode updates.

What's the canonical place to obtain them (ideally under the same terms as FSP)? Should this repo ship them, too?

**Comment by nate-desimone** [comment]
Hi @pgeorgi,

Microcode is available from https://downloadcenter.intel.com/download/28087/Linux-Processor-Microcode-Data-File

Intel distributes the FSP and microcode under the same license.

With Best Regards,
Nate

**Comment by i-c-o-n** [comment]
Hi Nate,

alas, the linked package is incomplete. I'm missing Microcode Updates for Bay Trail and Braswell, for instance. Rangeley might be absent too, not sure about all the CPUIDs. Also, the package is not updated regularly, so newer generations, e.g. Whiskey Lake, are missing too.

I understand that they don't belong into the FSP repo. Any pointer whom to ask for a more comprehensive distribution?

Actually, there is something that would be helpful in the FSP repo: A list of CPUIDs / steppings, each FSP is supposed to be compatible with. Didn't check right now, though, so maybe that exists already?

Nico
